export {
  KTO_AREA_CODES,
  KTO_REGIONS,
  TOTAL_KTO_REGION_COUNT,
  TOTAL_TRAVEL_CITY_COUNTY_COUNT,
  collectVisitedAreaCodes,
  collectVisitedCityCountyKeys,
  collectVisitedSigunguKeys,
  createKtoSigunguKey,
  getRegionByAreaCode,
  isKtoAreaCode,
  isTravelCityCountyKey,
  summarizeRegionVisits,
  type KtoAreaCode,
  type KtoSigunguKey,
  type Region,
  type RegionId,
  type RegionVisitSummary,
} from "./model/region";
